import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { CounterProvider } from '../context/CounterProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  team,
  analytics,
}: {
  children: React.ReactNode,
  team: React.ReactNode,
  analytics: React.ReactNode,
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CounterProvider>{children}</CounterProvider>
        <div>{team}</div>
        <div>{analytics}</div>
      </body>
    </html>
  )
}
